### ISSUE TITLE
Weird chunk loading issue

### ISSUE THREAD

**Issue by Evan-Britton** [cookiedragon234/PaperBin#20]
![image](https://user-images.githubusercontent.com/73912088/107337588-90a8a500-6a88-11eb-9ccf-0957869878da.png)
When I fly fast, my chunks look like this

**Comment by x4e** [comment]
Do you observe the same behaviour when PaperBin is not loaded?

**Comment by Evan-Britton** [comment]
No. I turned off paper bin and everything worked fine.

**Comment by x4e** [comment]
Can you send your paperbin config?

**Comment by Evan-Britton** [comment]
sure
[paperbin.txt](https://github.com/x4e/PaperBin/files/5952983/paperbin.txt)

**Comment by x4e** [comment]
Try disabling `antiNewChunks`, `lightUpdateRateLimit`, `antiChunkBan`, and `chunkLoadOptimisations`.

**Comment by Evan-Britton** [comment]
ok Ill try that

**Comment by Evan-Britton** [comment]
It seemed to be the antiNewChunks
Thx for the help!

**Comment by x4e** [comment]
Np
