### ISSUE TITLE
Question while running the jar compiled by my self

### ISSUE THREAD

**Issue by Rabbit0w0** [cookiedragon234/PaperBin#29]
When I was running the jar compiled by my self, it showed me an error

> Couldn't fetch jvmti instance (-3)

What should I do to solve this question?

The command lines that I used to compile

```Bash
cd src/main/rust
cargo build --release --target x86_64-pc-windows-gnu
cd ../../..

./gradlew build || exit 1
```

GCC Version: x86_64-8.1.0-posix-seh-rt_v6-rev0
Java Version: AdoptOpenJDK 11.0.10

**Comment by dG9hc3Q** [comment]
Latest PaperBin requires Java 15
