### ISSUE TITLE
Server Dosent want to start up using ccSpigot (paper fork with even more options)

### ISSUE THREAD

**Issue by megatron0001** [cookiedragon234/PaperBin#32]
Java: OpenJDK_Java_16
OS: Windows 10 pro
Command start.bat: java -Xms128M -Xmx1024M -jar PaperBin.jar ccSpigot.jar -agentpathLJvmClassHook.dll

![image](https://user-images.githubusercontent.com/82678869/122643268-cdf00400-d106-11eb-8c0a-b4a77d964727.png)

**Comment by x4e** [comment]
You wrote the `agentpath` flag wrong, your command should be:
```
java -agentpath:JvmClassHook.dll -Xms128M -Xmx1024M -jar PaperBin.jar ccSpigot.jar
```
