### ISSUE TITLE
Crash instantly at startup

### ISSUE THREAD

**Issue by abcdefg-bruh** [cookiedragon234/PaperBin#6]
**OS:** Windows 10
**Java Version:** 
java version "13.0.1" 2019-10-15
Java(TM) SE Runtime Environment (build 13.0.1+9)
Java HotSpot(TM) 64-Bit Server VM (build 13.0.1+9, mixed mode, sharing)

**Server Version:** Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**PaperBin 1.561**

```
C:\Users\x\Desktop\servers\c>java -Xmx1000m -Xms1000m -noverify -jar PaperBin.jar paper-1618.jar nogui

Java HotSpot(TM) 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.

Exception in thread "main" java.lang.NullPointerException
        at dev.binclub.paperbin.MainKt.main(Main.kt:29)
```

**Comment by abcdefg-bruh** [comment]
Gives this error when -noverify was removed.

```
C:\Users\x\Desktop\servers\c>java -Xmx1000m -Xms1000m -jar PaperBin.jar paper-1618.jar nogui

Exception in thread "main" java.lang.IllegalStateException: Disable the verifier
        at dev.binclub.paperbin.MainKt.main(Main.kt:23)
```

**Comment by abcdefg-bruh** [comment]
Using java 8 resolved the issue

**Comment by x4e** [comment]
Ive had reports of this bug on OpenJDK 1.8.0_242, if you are encountering this bug on OpenJDK I recommend you switch to OpenJDK 1.8.0_252 as this is working fine

**Comment by x4e** [comment]
I’ve had reports that this error can occur if no valid JAVA_HOME environment variable is defined, so check that if you’re having this error.

I’ll be moving away from the attach api and instrumentation in the next release to fix these compatibility problems.
